### ISSUE TITLE
yml files clash when filesystem is not case-sensitive

### ISSUE THREAD

**Issue by JamesBelchamber** [DavidWittman/ansible-filebeat#1] opened 2016-03-07 15:52 UTC
```
fatal: [x.x.x.x]: FAILED! => {"failed": true, "msg": "/usr/local/etc/ansible/roles/DavidWittman.filebeat/tasks/RedHat.yml must be stored as a dictionary/hash"}
```

This happens on OS X, because HFS+ is not (by default) case-sensitive. Changing the names of the task yml files fixes the issue.

**Comment by DavidWittman** [comment] 2016-03-07 22:19
Thanks James... Could you give me some more info on how to reproduce this issue and why renaming these files fixes the issue?

**Comment by JamesBelchamber** [comment] 2016-03-07 22:32
Sure. When you use `include_vars: x.yml` from a yaml file in `tasks/` it will include `tasks/x.yml`. If that doesn't exist, it will move on to `vars/x.yml`. This is probably a vestigial relic from when Ansible was less structured, but it is expected behaviour.

On OS X the default filesystem is not case-sensitive, so `RedHat.yml` and 'redhat.yml' are essentially the same file. This results in the line `include_vars: RedHat.yml` including `tasks/redhat.yml`, which is not what you intended and results in the error in the original post.

It's hard to test this if you don't have access to a case-insensitive filesystem but you're likely to be able to reproduce it by renaming `RedHat.yml` to `redhat.yml` (or vice versa) and testing.

EDIT: GitHub encourages you to reply via email, but when you do it doesn't support markdown -_-

**Comment by DavidWittman** [comment] 2016-03-07 22:34
Ah okay... That makes sense. I'll do some more testing tonight and get this merged in. Thanks again.

**Comment by DavidWittman** [comment] 2016-03-08 01:20
@JamesBelchamber what version of Ansible are you using?

We're using `with_first_found` here, so it should be passing the absolute path to the file into `include_vars`. In other words, there's no searching happening from the `include_vars` module, it should all be taken care of by `with_first_found`. With that in mind, looking at [lib/ansible/plugins/lookup/first_found.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/lookup/first_found.py#L186-L191) reveals that the order should be:
- `templates/`
- `vars/`
- `files/`
- `.` (current directory)

This is true for Ansible 2.x and 1.9.x as far as I can tell, provided you are running these tasks as a role. Unfortunately I'm Mac-less until next week (long story), but I did some maneuvering on my Linux box to try to reproduce this issue and was unsuccessful:

```
# Create tasks/RedHat.yml under Linux to simulate case insensitivity
$ cp tasks/{redhat,RedHat}.yml
$ tree tasks/ vars/
tasks/
├── debian.yml
├── main.yml
├── redhat.yml
└── RedHat.yml
vars/
├── Debian.yml
├── main.yml
└── RedHat.yml
$ ansible-playbook test.yml -i hosts

PLAY [all] ******************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [redacted]

TASK: [ansible-filebeat | include_vars {{ item }}] **************************** 
ok: [redacted] => (item=/home/dw/Projects/ansible/roles/ansible-filebeat/vars/RedHat.yml)
```

Yet, when I move `vars/RedHat.yml`, it finds `tasks/RedHat.yml` like you are seeing and subsequently fails:

```
$ mv vars/{RedHat,lol}.yml
$ tree vars/ tasks/
vars/
├── Debian.yml
├── lol.yml
└── main.yml
tasks/
├── debian.yml
├── main.yml
├── redhat.yml
└── RedHat.yml
$ ansible-playbook test.yml -i hosts

PLAY [all] ******************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [redacted]

TASK: [ansible-filebeat | include_vars {{ item }}] **************************** 
fatal: [redacted] => /home/dw/Projects/ansible/roles/ansible-filebeat/tasks/RedHat.yml must be stored as a dictionary/hash
```

I'm not doubting that you're having issues, I'd just like to better understand _why_ this is happening, and possibly address this issue upstream. It could be a version or environment issue that I'm just not seeing here. That said, if we're unable to figure out exactly why this is happening, I'm also exploring changing this task to instead read:

```
- include_vars: "{{ item }}"                                                    
  with_first_found:                                                             
    - "../vars/{{ ansible_os_family }}.yml"                                    
    - "../vars/default.yml"
```

Let me know if that works for you.

**Comment by JamesBelchamber** [comment] 2016-03-08 09:25
So, it does seem we're getting different results. If I add to the main.yml a debug statement, like so:

```
- debug: msg="{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}.yml"
    - default.yml
```

I get the following:

```
TASK [DavidWittman.filebeat : debug] *******************************************
ok: [188.166.150.74] => (item=/usr/local/etc/ansible/roles/DavidWittman.filebeat/tasks/RedHat.yml) => {
    "item": "/usr/local/etc/ansible/roles/DavidWittman.filebeat/tasks/RedHat.yml",
    "msg": "/usr/local/etc/ansible/roles/DavidWittman.filebeat/tasks/RedHat.yml"
}
```

So it sounds like our Ansible installations are finding different things. I'll dig a bit deeper and see why.

```
$ ansible --version
ansible 2.0.1.0
  config file =
  configured module search path = Default w/o overrides
```

**Comment by JamesBelchamber** [comment] 2016-03-08 12:02
_sigh_ I think I've found the issue. This is the code that `with_first_found` runs to find the file:

```
                    for subdir in ('templates', 'vars', 'files'):
                        path = self._loader.path_dwim_relative(roledir, subdir, fn)
                        raise AnsibleLookupError(path)
                        if os.path.exists(path):
                            return [path]
```

On my machine that code will always return the path `$roledir/tasks/$fn` (I don't know why it isn't on yours). If you look at `path_dwim_relative` you'll see why:

```
            if isrole and not source.endswith(dirname):
                # look in role's tasks dir w/o dirname
                search.append(self.path_dwim(os.path.join(basedir, 'tasks', source)))
```

When I run the role, this code is run (`isrole` is established further up the function) and as such, on the first iteration of the first bit of code `tasks` will always be searched before the next iteration searches `vars`. Although case-insensitivity **can** be an issue with Ansible in this case it isn't - it's simply that the file is named the same regardless of case.

I don't know why you're not seeing the same issue. I would recommend changing the filenames anyway, but this is obviously an Ansible bug. I'll raise it, but because of how obscure it is I don't expect it to be fixed quickly!

**Comment by DavidWittman** [comment] 2016-03-08 17:43
@JamesBelchamber thanks for opening that issue upstream. I suppose I should have made sure I was using the latest version of Ansible before asking you which version you're using :). As soon as I switched from 1.9.x to 2.0.x I was able to reproduce the issue, so this seems to be a regression of sorts.

Would you be opposed to changing your PR to instead specify the vars path in `with_first_found`? Like so:

``` diff
--- a/tasks/main.yml
+++ b/tasks/main.yml
@@ -1,8 +1,8 @@
 ---
 - include_vars: "{{ item }}"
   with_first_found:
-    - "{{ ansible_os_family }}.yml"
-    - default.yml
+    - "../vars/{{ ansible_os_family }}.yml"
+    - "../vars/default.yml"

 - include: redhat.yml
   when: ansible_os_family == 'RedHat'
```

This way we are explicit about which files we're trying to include variables from and are (hopefully) not subject to these types of search path changes in the future. With this method we can also avoid having to prefix any additional tasks with `setup` in the future as well.

**Comment by JamesBelchamber** [comment] 2016-03-16 08:30
Changed :)

**Closed as completed** 2016-03-16 17:28 UTC
